/**
 * scripts/backup.js
 *
 * Two-level backup system for Panorama Informativo.
 *
 * Usage:
 *   npm run backup -- --quick     Quick backup: schema + config tables as JSON
 *   npm run backup -- --full      Full backup: complete pg_dump with data
 *   npm run backup                Defaults to --quick
 */
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { execSync, spawnSync } from 'child_process';
import pg from 'pg';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
dotenv.config({ path: path.join(ROOT, '.env') });

const { Pool } = pg;
const pool = new Pool({ connectionString: process.env.DATABASE_URL });

const BACKUPS_DIR = path.join(ROOT, 'backups');
const BACKUPS_COMPLETE_DIR = path.join(BACKUPS_DIR, 'complete');
const SCHEMA_BASELINE = path.join(ROOT, 'schema_baseline.sql');
const SCHEMA_MANIFEST = path.join(ROOT, 'schema_manifest.json');
const DATABASE_MAP = path.join(ROOT, 'docs', 'DATABASE_MAP.md');

function timestamp() {
  return new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
}

function parseDbUrl(url) {
  const match = url.match(/postgres(?:ql)?:\/\/([^:]+):([^@]+)@([^:\/]+):?(\d*)\/?([^?]*)/);
  if (!match) throw new Error('Invalid DATABASE_URL format');
  return {
    user: match[1],
    password: match[2],
    host: match[3],
    port: match[4] || '5432',
    database: match[5] || 'postgres',
  };
}

// ── Quick backup ──────────────────────────────────────────────────────────────
async function quickBackup() {
  console.log('[backup] Starting QUICK backup...');
  fs.mkdirSync(BACKUPS_DIR, { recursive: true });

  const db = parseDbUrl(process.env.DATABASE_URL);

  // 1. Regenerate schema_baseline.sql via pg_dump --schema-only
  console.log('[backup] Running pg_dump --schema-only...');
  const env = { ...process.env, PGPASSWORD: db.password };
  const dumpResult = spawnSync('pg_dump', [
    '--schema-only',
    '--no-owner',
    '--no-privileges',
    '-h', db.host,
    '-p', db.port,
    '-U', db.user,
    '-d', db.database,
  ], { env, encoding: 'utf8' });

  if (dumpResult.status !== 0) {
    throw new Error(`pg_dump failed: ${dumpResult.stderr}`);
  }
  // Clean incompatible parameters for PostgreSQL 15 compatibility (e.g. from pg_dump v17/18)
  const cleanSql = dumpResult.stdout.replace(/SET transaction_timeout = 0;/g, '-- SET transaction_timeout = 0; (commented out for PostgreSQL 15 compatibility)');
  fs.writeFileSync(SCHEMA_BASELINE, cleanSql, 'utf8');
  console.log(`[backup] ✓ schema_baseline.sql updated (${(cleanSql.length / 1024).toFixed(1)} KB)`);

  // 2. Export config/reference tables to JSON
  const client = await pool.connect();
  try {
    const tables = [
      { name: 'rss_sources', file: path.join(BACKUPS_DIR, 'rss_sources.json') },
      { name: 'categories',  file: path.join(BACKUPS_DIR, 'categories.json') },
      { name: 'settings',    file: path.join(BACKUPS_DIR, 'settings.json') },
    ];

    for (const { name, file } of tables) {
      const { rows } = await client.query(`SELECT * FROM ${name} ORDER BY 1`);
      fs.writeFileSync(file, JSON.stringify(rows, null, 2), 'utf8');
      console.log(`[backup] ✓ ${name}.json exported (${rows.length} rows)`);
    }
  } finally {
    client.release();
  }

    // 3. Update schema_manifest.json
    const client2 = await pool.connect();
    try {
      const { rows: tables2 } = await client2.query(`SELECT COUNT(*) FROM pg_tables WHERE schemaname='public'`);
      const { rows: views } = await client2.query(`SELECT COUNT(*) FROM pg_views WHERE schemaname='public'`);
      const { rows: indexes } = await client2.query(`SELECT COUNT(*) FROM pg_indexes WHERE schemaname='public'`);

      // Compute SHA-256 of the freshly generated baseline
      const baselineContent = fs.readFileSync(SCHEMA_BASELINE, 'utf8');
      const baselineHash = crypto.createHash('sha256').update(baselineContent).digest('hex');

      let gitCommit = null;
      try { gitCommit = execSync('git rev-parse HEAD', { cwd: ROOT, encoding: 'utf8' }).trim(); } catch {}

      let manifest = {};
      if (fs.existsSync(SCHEMA_MANIFEST)) {
        manifest = JSON.parse(fs.readFileSync(SCHEMA_MANIFEST, 'utf8'));
      }
      manifest.generated_at = new Date().toISOString();
      manifest.baseline_status = 'OFFICIAL';
      manifest.baseline_sha256 = baselineHash;
      manifest.git_commit = gitCommit;
      manifest.generator_version = 'backup.js v1';
      manifest.tables_count = parseInt(tables2[0].count);
      manifest.views_count = parseInt(views[0].count);
      manifest.indexes_count = parseInt(indexes[0].count);
      manifest.baseline_note = 'Generated by npm run backup -- --quick. Represents the live schema at the time of backup.';

      fs.writeFileSync(SCHEMA_MANIFEST, JSON.stringify(manifest, null, 2), 'utf8');
      console.log(`[backup] ✓ schema_manifest.json updated → baseline_status: OFFICIAL (sha256: ${baselineHash.slice(0, 12)}...)`);
    } finally {
      client2.release();
    }

  console.log('[backup] 🎉 Quick backup complete.');
}

// ── Full backup ───────────────────────────────────────────────────────────────
async function fullBackup() {
  console.log('[backup] Starting FULL backup...');
  fs.mkdirSync(BACKUPS_COMPLETE_DIR, { recursive: true });

  const db = parseDbUrl(process.env.DATABASE_URL);
  const ts = timestamp();
  const outputFile = path.join(BACKUPS_COMPLETE_DIR, `backup_${ts}.sql`);

  console.log(`[backup] Running pg_dump (full data) → ${path.basename(outputFile)}...`);
  const env = { ...process.env, PGPASSWORD: db.password };
  const dumpResult = spawnSync('pg_dump', [
    '--no-owner',
    '--no-privileges',
    '-h', db.host,
    '-p', db.port,
    '-U', db.user,
    '-d', db.database,
  ], { env, encoding: 'utf8', maxBuffer: 500 * 1024 * 1024 });

  if (dumpResult.status !== 0) {
    throw new Error(`pg_dump failed: ${dumpResult.stderr}`);
  }

  fs.writeFileSync(outputFile, dumpResult.stdout, 'utf8');
  const sizeMB = (dumpResult.stdout.length / (1024 * 1024)).toFixed(2);
  console.log(`[backup] ✓ Full backup saved: ${path.basename(outputFile)} (${sizeMB} MB)`);

  // Also run quick backup to keep schema_baseline.sql and JSON exports up to date
  await quickBackup();

  console.log('[backup] 🎉 Full backup complete.');
}

// ── Entry point ───────────────────────────────────────────────────────────────
async function run() {
  const arg = process.argv[2];
  const isFull = arg === '--full';

  try {
    if (isFull) {
      await fullBackup();
    } else {
      await quickBackup();
    }
  } catch (err) {
    console.error('[backup] ❌ Backup failed:', err.message);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

run();
